package com.raffenio.model;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Person {

    Logger log = LoggerFactory.getLogger(Person.class);
    //1 - This is a simple class with getters and setters
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String lastName;
    @Getter
    @Setter
    private boolean alive;

    @Getter(value = AccessLevel.PRIVATE)
    @Setter(value = AccessLevel.PRIVATE)
    private String nickname;


    public void foo(){
        setNickname("@raffenio"); // this is fine because we are in the same class
        String nick = getNickname(); // this is fine because we are in the same class
        log.info("Nickname: {}", nick);
    }


    //we can generate getters and setters manually or using lombok

    //This code is commented out to show how to use lombok
    //will be autogenerated by lombok
    /*
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public boolean isAlive() {
        return alive;
    }

    public void setAlive(boolean alive) {
        this.alive = alive;
    }
    */
}
