package com.raffenio.model;

import lombok.NonNull;

public class TwitterAccount {
	private String username;
	
	//we are tellint the constructor that username should not be null
	public TwitterAccount(@NonNull String username) {
		super();
		
		//this code is generated by lombok
		//if (param == null) throw new NullPointerException("param is marked non-null but is null"); 
		//and will be inserted at the very top of your method. 
		//For constructors, the null-check will be inserted immediately following any explicit this() or super() calls.
		
		
		this.username = username;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	
}
